[project]
name = "binderdash-backend"
version = "0.1.0"
description = "Backend for binderdash"
dependencies = [
    "fastapi",
    "httpx",
    "uvicorn[standard]",
    "pydantic-settings",
    "pandas",
    "bcrypt",
    "python-jose[cryptography]",
    "python-multipart",
    "requests",
    "biopython",
    "tmtools",
    "dnachisel",
    "authlib",
    "python-pam",
    "itsdangerous",
]

[tool.pytest.ini_options]
pythonpath = [".."]
